# Generated by Django 3.2.7 on 2021-10-27 12:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_amount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='生産量')),
                ('material_amount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='消費量')),
                ('work_in_process', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='仕掛量')),
                ('defective', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='仕損じ量')),
                ('term_begin', models.DateField(blank=True, verbose_name='開始日')),
                ('term_end', models.DateField(blank=True, verbose_name='締め日')),
                ('cost_note', models.TextField(blank=True, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='会社名')),
                ('post', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator(message='７桁の数字を入力してください。', regex='^[0-9]+$')], verbose_name='郵便番号')),
                ('address', models.CharField(max_length=100, verbose_name='住所')),
                ('tel', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='10桁以上の数字を入力してください。', regex='^[0-9]+$')], verbose_name='電話番号')),
                ('fax', models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='10桁の数字を入力してください。', regex='^[0-9]+$')], verbose_name='FAX番号')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator(message='無効な文字列が入っています。', regex='^[a-zA-Z0-9_+-]+(.[a-zA-Z0-9_+-]+)*@([a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]*\\.)+[a-zA-Z]{2,}$')], verbose_name='メールアドレス')),
                ('entry', models.DateTimeField(auto_now=True, verbose_name='登録日')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='品名')),
                ('unit', models.CharField(choices=[('GR', 'グラム'), ('KG', 'キログラム'), ('CM', 'センチメートル'), ('MT', 'メートル'), ('ML', 'ミリリットル'), ('LT', 'リットル'), ('QT', '個'), ('ST', '枚'), ('NU', '本')], max_length=2, verbose_name='単位')),
                ('entry', models.DateTimeField(auto_now=True, verbose_name='登録日')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.category', verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='材料名')),
                ('division', models.CharField(choices=[('FD', '原材料'), ('PT', '部品'), ('SD', '補助資材'), ('XX', 'その他')], max_length=2, verbose_name='区分')),
                ('unit', models.CharField(choices=[('GR', 'グラム'), ('KG', 'キログラム'), ('CM', 'センチメートル'), ('MT', 'メートル'), ('ML', 'ミリリットル'), ('LT', 'リットル'), ('QT', '個'), ('ST', '枚'), ('NU', '本')], max_length=2, verbose_name='単位')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivering', models.CharField(choices=[('HD', '手渡し'), ('DV', '配送'), ('CR', '搬入'), ('XX', 'その他')], max_length=2, verbose_name='引渡し方法')),
                ('unit', models.CharField(choices=[('GR', 'グラム'), ('KG', 'キログラム'), ('CM', 'センチメートル'), ('MT', 'メートル'), ('ML', 'ミリリットル'), ('LT', 'リットル'), ('QT', '個'), ('ST', '枚'), ('NU', '本')], max_length=2, verbose_name='単位')),
                ('amount', models.PositiveIntegerField(verbose_name='セット数')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.item', verbose_name='品名')),
            ],
        ),
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='会社名')),
                ('name', models.CharField(max_length=50, verbose_name='担当者名')),
                ('post', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator(message='７桁の数字を入力してください。', regex='^[0-9]+$')], verbose_name='郵便番号')),
                ('address', models.CharField(max_length=100, verbose_name='住所')),
                ('tel', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='10桁以上の数字を入力してください。', regex='^[0-9]+$')], verbose_name='電話番号')),
                ('fax', models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='10桁の数字を入力してください。', regex='^[0-9]+$')], verbose_name='FAX番号')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator(message='無効な文字列が入っています。', regex='^[a-zA-Z0-9_+-]+(.[a-zA-Z0-9_+-]+)*@([a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]*\\.)+[a-zA-Z]{2,}$')], verbose_name='メールアドレス')),
                ('entry', models.DateTimeField(auto_now=True, verbose_name='登録日')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='Warehousing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='入庫日')),
                ('quantity', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='数量')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='税抜価額')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.cost', verbose_name='原価')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.material', verbose_name='材料名')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='仕入数量')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('warehousing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.warehousing', verbose_name='材料名')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(verbose_name='注文日')),
                ('order_amount', models.PositiveIntegerField(default=0, verbose_name='注文数')),
                ('settlement', models.CharField(choices=[('CA', '現金決済'), ('CC', 'クレジットカード決済'), ('RC', '掛取引'), ('AN', 'その他')], max_length=2, verbose_name='決済方法')),
                ('total_price', models.PositiveIntegerField(verbose_name='販売単価')),
                ('sales_tax', models.PositiveIntegerField(verbose_name='消費税額')),
                ('commission', models.PositiveIntegerField(verbose_name='1製品あたりの手数料')),
                ('how_to_give', models.CharField(choices=[('HD', '手渡し'), ('DV', '配送'), ('CR', '搬入'), ('XX', 'その他')], max_length=2, verbose_name='引き渡し方法')),
                ('giving_date', models.DateTimeField(verbose_name='引き渡し日')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.customer', verbose_name='得意先')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.product', verbose_name='製品名')),
            ],
        ),
        migrations.CreateModel(
            name='Orderer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='担当者名')),
                ('tel', models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='10桁の数字を入力してください。', regex='^[0-9]+$')], verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator(message='無効な文字列が入っています。', regex='^[a-zA-Z0-9_+-]+(.[a-zA-Z0-9_+-]+)*@([a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]*\\.)+[a-zA-Z]{2,}$')], verbose_name='メールアドレス')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.customer', verbose_name='会社名')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='vender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.vender', verbose_name='仕入先'),
        ),
        migrations.AddField(
            model_name='cost',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.material', verbose_name='材料名'),
        ),
        migrations.AddField(
            model_name='cost',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.product', verbose_name='製品名'),
        ),
    ]
