# Generated by Django 3.2.7 on 2021-09-22 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vender',
            name='post',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='エラーメッセージ', regex='^[0-9]+$')], verbose_name='郵便番号'),
        ),
    ]
