# Generated by Django 3.2.7 on 2021-11-03 10:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.category', verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='orderer',
            name='tel',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='10桁の数字を入力してください。', regex='^[0-9]+$')], verbose_name='電話番号'),
        ),
    ]
