# Generated by Django 3.2.7 on 2021-09-22 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_alter_vender_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vender',
            name='post',
            field=models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator(message='７桁の数字を入力してください。', regex='^[0-9]+$')], verbose_name='郵便番号'),
        ),
    ]
