# Generated by Django 3.2.7 on 2021-09-24 01:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0003_alter_vender_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='settlement',
        ),
        migrations.AlterField(
            model_name='sale',
            name='order_date',
            field=models.DateTimeField(auto_now=True, verbose_name='注文日'),
        ),
        migrations.AlterField(
            model_name='vender',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name='会社名'),
        ),
        migrations.AlterField(
            model_name='vender',
            name='fax',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='10桁の数字を入力してください。', regex='^[0-9]+$')], verbose_name='FAX番号'),
        ),
        migrations.AlterField(
            model_name='vender',
            name='tel',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='10桁以上の数字を入力してください。', regex='^[0-9]+$')], verbose_name='電話番号'),
        ),
    ]
