# Generated by Django 3.2.7 on 2021-11-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0003_auto_20211103_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousing',
            name='cost',
        ),
    ]
