# Generated by Django 3.2.7 on 2021-11-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0004_remove_warehousing_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivering',
        ),
        migrations.AddField(
            model_name='sale',
            name='delivering',
            field=models.CharField(choices=[('HD', '手渡し'), ('DV', '配送'), ('CR', '搬入'), ('XX', 'その他')], default=1, max_length=2, verbose_name='引渡し方法'),
            preserve_default=False,
        ),
    ]
