# Generated by Django 3.2.7 on 2021-09-24 01:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0004_auto_20210924_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator(message='無効な文字列が入っています。', regex='^[a-zA-Z0-9_+-]+(.[a-zA-Z0-9_+-]+)*@([a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]*\\.)+[a-zA-Z]{2,}$')], verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fax',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='10桁の数字を入力してください。', regex='^[0-9]+$')], verbose_name='FAX番号'),
        ),
        migrations.AlterField(
            model_name='client',
            name='post',
            field=models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator(message='７桁の数字を入力してください。', regex='^[0-9]+$')], verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='10桁以上の数字を入力してください。', regex='^[0-9]+$')], verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100, verbose_name='材料名'),
        ),
        migrations.AlterField(
            model_name='vender',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator(message='無効な文字列が入っています。', regex='^[a-zA-Z0-9_+-]+(.[a-zA-Z0-9_+-]+)*@([a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]*\\.)+[a-zA-Z]{2,}$')], verbose_name='メールアドレス'),
        ),
    ]
