# Generated by Django 3.2.7 on 2021-11-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0005_auto_20211110_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='delivering',
        ),
    ]
