# Generated by Django 3.2.7 on 2021-10-06 11:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0006_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='会社名')),
                ('post', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator(message='７桁の数字を入力してください。', regex='^[0-9]+$')], verbose_name='郵便番号')),
                ('address', models.CharField(max_length=100, verbose_name='住所')),
                ('tel', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='10桁以上の数字を入力してください。', regex='^[0-9]+$')], verbose_name='電話番号')),
                ('fax', models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='10桁の数字を入力してください。', regex='^[0-9]+$')], verbose_name='FAX番号')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator(message='無効な文字列が入っています。', regex='^[a-zA-Z0-9_+-]+(.[a-zA-Z0-9_+-]+)*@([a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]*\\.)+[a-zA-Z]{2,}$')], verbose_name='メールアドレス')),
                ('entry', models.DateTimeField(auto_now=True, verbose_name='登録日')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='Orderer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='担当者名')),
                ('tel', models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='10桁の数字を入力してください。', regex='^[0-9]+$')], verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator(message='無効な文字列が入っています。', regex='^[a-zA-Z0-9_+-]+(.[a-zA-Z0-9_+-]+)*@([a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]*\\.)+[a-zA-Z]{2,}$')], verbose_name='メールアドレス')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.customer')),
            ],
        ),
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.customer'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
