# Generated by Django 3.2.7 on 2021-11-10 11:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0006_remove_sale_delivering'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='sale',
            name='orderer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='costs.orderer', verbose_name='得意先'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='post',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator(message='７桁の数字を入力してください。', regex='^[0-9]+$')], verbose_name='郵便番号'),
        ),
    ]
