# Generated by Django 3.2.7 on 2021-11-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0007_auto_20211110_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='how_to_give',
            field=models.CharField(choices=[('HD', '手渡し'), ('DV', '配送'), ('CR', '直接納入'), ('XX', 'その他')], max_length=2, verbose_name='引き渡し方法'),
        ),
    ]
