# Generated by Django 3.2.7 on 2021-10-06 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0007_auto_20211006_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousing',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='costs.material'),
        ),
    ]
