# Generated by Django 3.2.7 on 2021-10-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0009_alter_warehousing_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousing',
            name='date',
            field=models.DateTimeField(verbose_name='入庫日'),
        ),
    ]
