# Generated by Django 3.2.7 on 2021-11-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0010_auto_20211117_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='term_month',
            field=models.CharField(choices=[('1月1', 'Jan'), ('2', 'Feb'), ('3', 'Mat'), ('4', 'Apl'), ('5', 'May'), ('6', 'Jon'), ('7', 'Jra'), ('8', 'Aug'), ('9', 'Sep'), ('10', 'Oct'), ('11', 'Nob'), ('12', 'Dec')], max_length=3, verbose_name='開始月'),
        ),
    ]
