# Generated by Django 3.2.7 on 2021-10-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0010_alter_warehousing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousing',
            name='date',
            field=models.DateField(verbose_name='入庫日'),
        ),
    ]
