# Generated by Django 3.2.7 on 2021-10-07 13:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0011_alter_warehousing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousing',
            name='unit',
        ),
        migrations.AddField(
            model_name='warehousing',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='税抜価額'),
        ),
        migrations.AlterField(
            model_name='warehousing',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.material', verbose_name='材料名'),
        ),
        migrations.AlterField(
            model_name='warehousing',
            name='quantity',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='数量'),
        ),
    ]
