# Generated by Django 3.2.7 on 2021-11-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0011_alter_cost_term_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='term_month',
            field=models.CharField(choices=[('1', '1月'), ('2', '2月'), ('3', '3月'), ('4', '4月'), ('5', '5月'), ('6', '6月'), ('7', '7月'), ('8', '8月'), ('9', '9月'), ('10', '10月'), ('11', '11月'), ('12', '12月')], max_length=2, verbose_name='開始月'),
        ),
    ]
