# Generated by Django 3.2.7 on 2021-10-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0012_auto_20211007_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='term_begin',
            field=models.DateField(verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='term_end',
            field=models.DateField(verbose_name='締め日'),
        ),
    ]
