# Generated by Django 3.2.7 on 2021-10-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0013_auto_20211008_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='division',
            field=models.CharField(choices=[('FD', '原材料'), ('PT', '部品'), ('SD', '補助資材'), ('XX', 'その他')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('GR', 'グラム'), ('KG', 'キログラム'), ('CM', 'センチメートル'), ('MT', 'メートル'), ('ML', 'ミリリットル'), ('LT', 'リットル'), ('QT', '個数')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='division',
            field=models.CharField(choices=[('HD', '手渡し'), ('DV', '配送'), ('CR', '搬入'), ('XX', 'その他')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('GR', 'グラム'), ('KG', 'キログラム'), ('CM', 'センチメートル'), ('MT', 'メートル'), ('ML', 'ミリリットル'), ('LT', 'リットル'), ('QT', '個数')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='settlement',
            field=models.CharField(choices=[('CA', '現金決済'), ('CC', 'クレジットカード決済'), ('RC', '掛取引'), ('AN', 'その他')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
