# Generated by Django 3.2.7 on 2021-10-09 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0015_auto_20211008_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='division',
            new_name='delivering',
        ),
    ]
