# Generated by Django 3.2.7 on 2021-10-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0016_rename_division_product_delivering'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='material_unit',
            field=models.CharField(choices=[('GR', 'グラム'), ('KG', 'キログラム'), ('CM', 'センチメートル'), ('MT', 'メートル'), ('ML', 'ミリリットル'), ('LT', 'リットル'), ('QT', '個'), ('ST', '枚'), ('NU', '本')], default=1, max_length=2, verbose_name='単位'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cost',
            name='product_unit',
            field=models.CharField(choices=[('GR', 'グラム'), ('KG', 'キログラム'), ('CM', 'センチメートル'), ('MT', 'メートル'), ('ML', 'ミリリットル'), ('LT', 'リットル'), ('QT', '個'), ('ST', '枚'), ('NU', '本')], default=1, max_length=2, verbose_name='単位'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('GR', 'グラム'), ('KG', 'キログラム'), ('CM', 'センチメートル'), ('MT', 'メートル'), ('ML', 'ミリリットル'), ('LT', 'リットル'), ('QT', '個'), ('ST', '枚'), ('NU', '本')], max_length=2, verbose_name='単位'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivering',
            field=models.CharField(choices=[('HD', '手渡し'), ('DV', '配送'), ('CR', '搬入'), ('XX', 'その他')], max_length=2, verbose_name='引渡し方法'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('GR', 'グラム'), ('KG', 'キログラム'), ('CM', 'センチメートル'), ('MT', 'メートル'), ('ML', 'ミリリットル'), ('LT', 'リットル'), ('QT', '個'), ('ST', '枚'), ('NU', '本')], max_length=2, verbose_name='単位'),
        ),
    ]
