# Generated by Django 3.2.7 on 2021-10-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0017_auto_20211012_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderer',
            name='note',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='sale',
            name='note',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='how_to_give',
            field=models.CharField(choices=[('HD', '手渡し'), ('DV', '配送'), ('CR', '搬入'), ('XX', 'その他')], max_length=2, verbose_name='引き渡し方法'),
        ),
    ]
