# Generated by Django 3.2.7 on 2021-10-13 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0019_auto_20211013_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='material_unit',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='product_unit',
        ),
        migrations.AlterField(
            model_name='cost',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_material', to='costs.material', verbose_name='材料名'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_product', to='costs.product', verbose_name='製品名'),
        ),
    ]
