# Generated by Django 3.2.7 on 2021-10-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0021_auto_20211013_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='term_begin',
            field=models.DateField(blank=True, verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='term_end',
            field=models.DateField(blank=True, verbose_name='締め日'),
        ),
    ]
