# Generated by Django 3.2.7 on 2021-10-15 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0022_auto_20211013_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.material', verbose_name='材料名'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.product', verbose_name='製品名'),
        ),
        migrations.AlterField(
            model_name='warehousing',
            name='cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_material', to='costs.cost', verbose_name='原価'),
        ),
        migrations.AlterField(
            model_name='warehousing',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_material', to='costs.material', verbose_name='材料名'),
        ),
    ]
