# Generated by Django 3.2.7 on 2021-10-15 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0023_auto_20211015_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousing',
            name='cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.cost', verbose_name='原価'),
        ),
        migrations.AlterField(
            model_name='warehousing',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costs.material', verbose_name='材料名'),
        ),
    ]
